baseURL = 'https://jo-gangeun.github.io/zomggang-devblog/'
title = 'Zomggang Devblog'
theme = 're-terminal'
languageCode = 'ko'
defaultContentLanguage = 'ko'
defaultContentLanguageInSubdir = true
pagination.pagerSize = 5

[params]
  contentTypeName = "posts"
  themeColor = "orange"
  showMenuItems = 3
  fullWidthTheme = false
  centerTheme = true
  readingTime = true


[languages]

[languages.ko]
languageName = "í•œêµ­ì–´"
weight = 1
contentDir = "content/ko"

[languages.en]
languageName = "English"
weight = 2
contentDir = "content/en"

[languages.ja]
languageName = "æ—¥æœ¬èª"
weight = 3
contentDir = "content/jp"

    [languages.ko.params.logo]
      logoText = "HOMEğŸ•ï¸"
    [languages.en.params.logo]
      logoText = "HOMEğŸ•ï¸"
    [languages.ja.params.logo]
      logoText = "HOMEğŸ•ï¸"
